import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';

import { routes } from './app.routes';
import { DRAWER_SHELL_TOKEN } from '@fibo-ui/cdk';
import {
  OverlayDrawerShellComponent,
  provideOverlays,
  withShell,
} from '@fibo-ui/components';
import {
  ArrowRight,
  Apple,
  Briefcase,
  Bell,
  BookOpen,
  Bug,
  Calendar,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  File,
  FileText,
  Folder,
  Globe,
  GitBranch,
  House,
  Lock,
  Code,
  Cloud,
  Container,
  CupSoda,
  Database,
  DollarSign,
  Droplet,
  Check,
  Component,
  LUCIDE_ICONS,
  LucideIconProvider,
  Leaf,
  Mail,
  LayoutTemplate,
  List,
  Menu,
  MessageSquare,
  Dot,
  PanelRight,
  Search,
  Settings,
  ShieldCheck,
  Server,
  Terminal,
  User,
  UserCheck,
  Wrench,
  X,
  CirclePlus,
  Moon,
  Sun,
  Monitor,
  CalendarDays,
  CalendarRange,
  TextCursorInput,
  ToggleLeft,
  Loader,
  LogOut,
  MousePointerClick,
  Layers,
  MapPin,
  SquareMousePointer,
  Info,
  Network,
  Package,
  Eye,
  EyeOff,
} from 'lucide-angular';

const icons = {
  ArrowRight,
  File,
  House,
  Menu,
  UserCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  X,
  Search,
  Folder,
  Globe,
  CirclePlus,
  Moon,
  Sun,
  Monitor,
  CalendarDays,
  CalendarRange,
  Apple,
  Briefcase,
  Bell,
  BookOpen,
  Bug,
  Calendar,
  Check,
  CheckSquare,
  Circle,
  Cloud,
  Code,
  Component,
  Container,
  CupSoda,
  Database,
  DollarSign,
  Droplet,
  FileText,
  GitBranch,
  LayoutTemplate,
  Leaf,
  List,
  Lock,
  Mail,
  MessageSquare,
  Dot,
  PanelRight,
  Settings,
  ShieldCheck,
  Server,
  Terminal,
  User,
  Wrench,
  TextCursorInput,
  ToggleLeft,
  Loader,
  LogOut,
  MousePointerClick,
  Layers,
  MapPin,
  SquareMousePointer,
  Info,
  Network,
  Package,
  Eye,
  EyeOff,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(),
    provideOverlays(withShell(DRAWER_SHELL_TOKEN, OverlayDrawerShellComponent)),
    { provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(icons) }
  ]
};
