import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';

import { routes } from './app.routes';
import {
  Apple,
  Bell,
  Bug,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  File,
  FileText,
  Folder,
  GitBranch,
  House,
  Lock,
  Code,
  Cloud,
  Container,
  CupSoda,
  Database,
  Droplet,
  Check,
  Component,
  LUCIDE_ICONS,
  LucideIconProvider,
  Leaf,
  LayoutTemplate,
  List,
  Menu,
  MessageSquare,
  Dot,
  PanelRight,
  Search,
  Settings,
  ShieldCheck,
  Server,
  Terminal,
  User,
  UserCheck,
  Wrench,
  X,
  CirclePlus,
  Moon,
  Sun,
  Monitor,
  CalendarDays,
  CalendarRange
} from 'lucide-angular';

const icons = {
  File,
  House,
  Menu,
  UserCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  X,
  Search,
  Folder,
  CirclePlus,
  Moon,
  Sun,
  Monitor,
  CalendarDays,
  CalendarRange,
  Apple,
  Bell,
  Bug,
  Calendar,
  Check,
  Circle,
  Cloud,
  Code,
  Component,
  Container,
  CupSoda,
  Database,
  Droplet,
  FileText,
  GitBranch,
  LayoutTemplate,
  Leaf,
  List,
  Lock,
  MessageSquare,
  Dot,
  PanelRight,
  Settings,
  ShieldCheck,
  Server,
  Terminal,
  User,
  Wrench,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(),
    { provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(icons) }
  ]
};
